name: build deploy actions
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: firebasedeploy
    # This job runs on Linux
    # https://medium.com/@puuga/deploy-to-firebase-hosting-with-github-actions-f795785fde6b
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the repository
          uses: actions/checkout@master
        - name: Set Node.js
          uses: actions/setup-node@master
          with:
            node-version: 10.x
        - name: Install dependencies
          run: yarn install
        - name: Build
          run: yarn run build
        - name: Deploy to Firebase
          uses: w9jds/firebase-action@master
          with:
            args: deploy --only hosting
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}    